name = "api-frontendista-cz"
type = "javascript"

account_id = "556f46decf146c2cfd5cc44150fb2557"
zone_id = "61b1f8d022953a18f9f9f82a155d1403"
compatibility_date = "2022-04-03"

workers_dev = true

[build]
command = "pnpm build:prod"
watch_dir = "app"

[build.upload]
format = "service-worker"

[env.staging]
route = "api.frontendista.cz/staging/*"
vars = { ENVIRONMENT = "staging", BASE_PATH = "staging" }

[env.production]
route = "api.frontendista.cz/v1/*"
vars = { ENVIRONMENT = "production", BASE_PATH = "v1" }

[miniflare]
watch = true
debug = true
build_command = "pnpm build"
