name: Staging

on: workflow_dispatch

jobs:
  tsc:
    runs-on: ubuntu-latest
    name: TypeScript type-checking

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: latest

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm tsc -noEmit

  deploy:
    runs-on: ubuntu-latest
    name: Deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: latest

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Deploy
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: "staging"
